### ISSUE TITLE
remove: Avoid annotating types for function expression parameters on catchError

### ISSUE THREAD

**Issue by bsutton** [tenhobi/effective_dart#31]
The effective dart linter generates an error on future.catchError:

```dart
 future
        .catchError((Object e, StackTrace st) => print('onErrr: $e'))
```
The .catchError method requires that you pass the types.

As such this rule needs to be explicitly ignored every time.

It would be good if the linter was smart enough to recognize this situation and suppress the lint.

**Comment by tenhobi** [comment]
Hi 👋 @bsutton.

I think this is due to this rule, right? https://dart-lang.github.io/linter/lints/avoid_types_on_closure_parameters.html

> AVOID annotating types for function expression parameters.
>
> Annotating types for function expression parameters is usually unnecessary because the parameter types can almost always be inferred from the context, thus making the practice redundant.

As the definition says, the type can be usually inferred from the context. If you want to handle specific errors, most of the time you pass a function there, which has types defined. Like there: https://dart.dev/guides/libraries/futures-error-handling#handling-specific-errors
Or you can, of course, suppress this rule in line, file or project level, as is described here: https://github.com/tenhobi/effective_dart#suppressing-lints

Anyway, I am not an author of those rules and this package only provides them. If you feel this functionality is wrong, please open an issue in https://github.com/dart-lang/linter
