### ISSUE TITLE
Using effective_dart with vscode on load shows error include_file_not_found

### ISSUE THREAD

**Issue by ghost** [tenhobi/effective_dart#32]
I do not know if the problem is with vscode although I suspect that it is some kind of configuration issue.  Here's the error I'm getting when I use effective_dart in some of my projects:

`The include file package:effective_dart/analysis_options.yaml in [...]analysis_options.yaml cannot be found.`

I've checked that the path is correct, if I change the line of the include and then change it back to exactly what it was before the problem will go away, but I have to do this every time I open this particular project.  Also I tried changing the include to use a specific version number and I have the same behavior on load.

Any idea what is going on?

**Comment by tenhobi** [comment]
Hi @VinceERS ✋, thanks for opening the issue.

I don't think so this is related to this package since there is a similar issue in the pedantic package https://github.com/dart-lang/pedantic/issues/52.

I tested using both pedantic and this package, and it didn't show any error, so I don't know how to help you. 🤷‍♂️

**Comment by ghost** [comment]
Ok thanks, it sounds like exactly the same problem!  I'll update with any changes, I thought that maybe it could have been a problem with vscode.
