### ISSUE TITLE
Explain the difference to pedantic

### ISSUE THREAD

**Issue by enyo** [tenhobi/effective_dart#38]
The README says that this is heavily influenced by pedantic. But it's unclear what the goal or difference is. It would be great if you could add a small sentence or paragraph to the README explaining the difference between the two, so it's easier to decide whether pedantic or effective should be used.

Thanks

**Comment by tenhobi** [comment]
The README says 

> This package provides linter rules corresponding to the guidelines in Effective Dart. You can easily see all enabled rules on the Supported Lint Rules site.

Which is exactly what it does -- this is a package to enforce guidelines from Effective Dart, e.g. https://dart.dev/guides/language/effective-dart

There is mention of the pedantic package because I have been inspired by it to create this package. :)

I don't know how or why to make things more clear. If you have some ideas, you can create a PR! 👍

**Comment by tenhobi** [comment]
I am closing the PR for now. If you have some additional things to say, let me know. 🙂
